#pragma once

template <class T>
class CProxy_IFanxianBandEvents : public IConnectionPointImpl<T, &__uuidof( _IFanxianBandEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
