#pragma once

template <class T>
class CProxy_IComActiveXObjEvents : public IConnectionPointImpl<T, &__uuidof(_IComActiveXObjEvents), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
