// ComicService.idl : IDL source for ComicService
//

// This file will be processed by the MIDL tool to
// produce the type library (ComicService.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

typedef[v1_enum]
[
    uuid(91A2B67C-6A4D-4117-A7A2-2174EA4BFA02),
    helpstring("Comic Service Custom Control Type"),
]
enum ServiceCustomControl
{
    [helpstring("Stop")]         COMIC_SERVICE_STOP = 0x81,
}ServiceCustomControl;

[
    object,
    uuid(AFB24CDD-6F94-4A7D-9449-9DF4C31B606B),
    dual,
    nonextensible,
    helpstring("IComicServiceObj Interface"),
    pointer_default(unique)
]
interface IComicServiceObj : IDispatch{
    [id(1), helpstring("method ProtectWnd")] HRESULT ProtectWnd([in] OLE_HANDLE hWnd, [in] OLE_COLOR clrDisabled);
    [id(2), helpstring("method UnProtectWnd")] HRESULT UnProtectWnd([in] OLE_HANDLE hWnd);
    [id(3), helpstring("method HeartBeat")] HRESULT HeartBeat([in] LONG curTicket);
    [id(4), helpstring("method UpdateSetupFileInfo")] HRESULT UpdateSetupFileInfo([in] LONG nSetupFilePid);
};
[
    uuid(1D7B6492-0112-4C41-8B2B-FCD9210FE0FE),
    version(1.0),
    helpstring("ComicService 1.0 Type Library")
]
library ComicServiceLib
{
    importlib("stdole2.tlb");
    [
        uuid(F59F3BEF-4A2B-4327-96EE-795E8FF1352F),
        helpstring("ComicServiceObj Class")
    ]
    coclass ComicServiceObj
    {
        [default] interface IComicServiceObj;
    };
};
