// This file was generated by WTL Dialog wizard 
// DlgButtons.h : Declaration of the CDlgFirst

#pragma once

#include "resource.h"       // main symbols
#include "DialogResizeEx.h"
#include "MyOpenGLWnd.h"

// CDlgFirst

class CDlgFirst : 
    public ATL::CDialogImpl<CDlgFirst>,
	public CWinDataExchange<CDlgFirst>,
    public CDialogResizeEx<CDlgFirst>
{
public:
    
public:
    CDlgFirst();
	~CDlgFirst();
	enum { IDD = IDD_FIRST };

    BEGIN_MSG_MAP(CDlgFirst)
        //DUMP_WINDOWS_MSG(__FILE__LINE__, DEAFULT_DUMP_FILTER_MESSAGES, _countof(DEAFULT_DUMP_FILTER_MESSAGES), uMsg, wParam, lParam)

		MESSAGE_HANDLER(WM_INITDIALOG, OnInitDialog)
        COMMAND_ID_HANDLER_EX(IDC_BTN_BASIC_OPENGL, OnBasicOpenGLDemoWnd)

        CHAIN_MSG_MAP(CDialogResize<CDlgFirst>)
        REFLECT_NOTIFICATIONS()
    END_MSG_MAP()

	BEGIN_DDX_MAP(CDlgFirst)
	END_DDX_MAP()

    BEGIN_DLGRESIZE_MAP(CDlgFirst)
        //DLGRESIZE_CONTROL(IDOK, DLSZ_MOVE_X)
        //DLGRESIZE_CONTROL(IDCANCEL, DLSZ_MOVE_X)
        //DLGRESIZE_CONTROL(IDC_BTN_ST, DLSZ_MOVE_X)
        //DLGRESIZE_CONTROL(IDC_BTN_SHADE, DLSZ_MOVE_X)
    END_DLGRESIZE_MAP()

private:
    FTL::CFOpenGLApp     m_OpenGLApp;
    CMyOpenGLWnd    m_MyOpenGLWnd;
public:
    LRESULT OnInitDialog(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled);
    void OnBasicOpenGLDemoWnd(UINT uNotifyCode, int nID, CWindow wndCtl);
};


