// This file was generated by WTL Dialog wizard 
// DlgButtons.cpp : Implementation of CDlgFirst

#include "stdafx.h"
#include "DlgFirst.h"

// CDlgFirst
CDlgFirst::CDlgFirst()
{
}

CDlgFirst::~CDlgFirst()
{
}

LRESULT CDlgFirst::OnInitDialog(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled)
{
	DoDataExchange();//m_BtnSt.SubclassWindow(GetDlgItem(IDC_BTN_ST));
    DlgResize_Init(FALSE);

    //m_OpenGLApp.Initialize();

	return 1;  // Let the system set the focus
}

void CDlgFirst::OnBasicOpenGLDemoWnd(UINT uNotifyCode, int nID, CWindow wndCtl)
{
    BOOL bRet = FALSE;
    if (!m_MyOpenGLWnd.IsWindow())
    {
        API_VERIFY(NULL != m_MyOpenGLWnd.Create(m_hWnd));
    }
    if (m_MyOpenGLWnd.IsWindow())
    {
        m_MyOpenGLWnd.ShowWindow(SW_SHOW);
    }
}

//LRESULT CDlgFirst::OnClickedOK(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled)
//{
//	DoDataExchange(TRUE);
//	EndDialog(wID);
//	return 0;
//}
//
//LRESULT CDlgFirst::OnClickedCancel(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled)
//{
//	EndDialog(wID);
//	return 0;
//}
