// This file was generated by WTL Dialog wizard 
// DlgButtons.cpp : Implementation of CDlgTranscode

#include "stdafx.h"
#include "DlgTranscode.h"

// CDlgTranscode
CDlgTranscode::CDlgTranscode()
{
}

CDlgTranscode::~CDlgTranscode()
{
}

LRESULT CDlgTranscode::OnInitDialog(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled)
{
	DoDataExchange();//m_BtnSt.SubclassWindow(GetDlgItem(IDC_BTN_ST));
    DlgResize_Init(FALSE);

	return 1;  // Let the system set the focus
}
