#pragma once

#include <stdidcmd.h>

#ifndef FTL_BASE_H
#  error ftlVSIPHelper.h requires ftlbase.h to be included first
#endif

namespace FTL
{
    class CFVSIPUtils
    {
    public:

        //获取 cmdidcmd.h 中定义的 CmdID 对应的字符串，在 IOleCommandTarget::QueryStatus 中判断 cmds[n].cmdID
        LPCTSTR static GetStdIdCommandtring(ULONG cmdID)
        {
            switch(cmdID)
            {
                HANDLE_CASE_RETURN_STRING(ECMD_TYPECHAR);
                HANDLE_CASE_RETURN_STRING(ECMD_BACKSPACE);
                HANDLE_CASE_RETURN_STRING(ECMD_RETURN);
                HANDLE_CASE_RETURN_STRING(ECMD_TAB);
                HANDLE_CASE_RETURN_STRING(ECMD_BACKTAB);
                HANDLE_CASE_RETURN_STRING(ECMD_DELETE);
                HANDLE_CASE_RETURN_STRING(ECMD_LEFT);
                HANDLE_CASE_RETURN_STRING(ECMD_LEFT_EXT);
                HANDLE_CASE_RETURN_STRING(ECMD_RIGHT);
                HANDLE_CASE_RETURN_STRING(ECMD_RIGHT_EXT);
                HANDLE_CASE_RETURN_STRING(ECMD_UP);
                HANDLE_CASE_RETURN_STRING(ECMD_UP_EXT);
                HANDLE_CASE_RETURN_STRING(ECMD_DOWN);
                HANDLE_CASE_RETURN_STRING(ECMD_DOWN_EXT);
                HANDLE_CASE_RETURN_STRING(ECMD_HOME);
                HANDLE_CASE_RETURN_STRING(ECMD_HOME_EXT);
                HANDLE_CASE_RETURN_STRING(ECMD_END);
                HANDLE_CASE_RETURN_STRING(ECMD_END_EXT);
                HANDLE_CASE_RETURN_STRING(ECMD_BOL);
                HANDLE_CASE_RETURN_STRING(ECMD_BOL_EXT);
                HANDLE_CASE_RETURN_STRING(ECMD_FIRSTCHAR);
                HANDLE_CASE_RETURN_STRING(ECMD_FIRSTCHAR_EXT);
                HANDLE_CASE_RETURN_STRING(ECMD_EOL);
                HANDLE_CASE_RETURN_STRING(ECMD_EOL_EXT);
                HANDLE_CASE_RETURN_STRING(ECMD_LASTCHAR);
                HANDLE_CASE_RETURN_STRING(ECMD_LASTCHAR_EXT);
                HANDLE_CASE_RETURN_STRING(ECMD_PAGEUP);
                HANDLE_CASE_RETURN_STRING(ECMD_PAGEUP_EXT);
                HANDLE_CASE_RETURN_STRING(ECMD_PAGEDN);
                HANDLE_CASE_RETURN_STRING(ECMD_PAGEDN_EXT);
                HANDLE_CASE_RETURN_STRING(ECMD_TOPLINE);
                HANDLE_CASE_RETURN_STRING(ECMD_TOPLINE_EXT);
                HANDLE_CASE_RETURN_STRING(ECMD_BOTTOMLINE);
                HANDLE_CASE_RETURN_STRING(ECMD_BOTTOMLINE_EXT);
                HANDLE_CASE_RETURN_STRING(ECMD_SCROLLUP);
                HANDLE_CASE_RETURN_STRING(ECMD_SCROLLDN);
                HANDLE_CASE_RETURN_STRING(ECMD_SCROLLPAGEUP);
                HANDLE_CASE_RETURN_STRING(ECMD_SCROLLPAGEDN);
                HANDLE_CASE_RETURN_STRING(ECMD_SCROLLLEFT);
                HANDLE_CASE_RETURN_STRING(ECMD_SCROLLRIGHT);
                HANDLE_CASE_RETURN_STRING(ECMD_SCROLLBOTTOM);
                HANDLE_CASE_RETURN_STRING(ECMD_SCROLLCENTER);
                HANDLE_CASE_RETURN_STRING(ECMD_SCROLLTOP);
                HANDLE_CASE_RETURN_STRING(ECMD_SELECTALL);
                HANDLE_CASE_RETURN_STRING(ECMD_SELTABIFY);
                HANDLE_CASE_RETURN_STRING(ECMD_SELUNTABIFY);
                HANDLE_CASE_RETURN_STRING(ECMD_SELLOWCASE);
                HANDLE_CASE_RETURN_STRING(ECMD_SELUPCASE);
                HANDLE_CASE_RETURN_STRING(ECMD_SELTOGGLECASE);
                HANDLE_CASE_RETURN_STRING(ECMD_SELTITLECASE);
                HANDLE_CASE_RETURN_STRING(ECMD_SELSWAPANCHOR);
                HANDLE_CASE_RETURN_STRING(ECMD_GOTOLINE);
                HANDLE_CASE_RETURN_STRING(ECMD_GOTOBRACE);
                HANDLE_CASE_RETURN_STRING(ECMD_GOTOBRACE_EXT);
                HANDLE_CASE_RETURN_STRING(ECMD_GOBACK);
                HANDLE_CASE_RETURN_STRING(ECMD_SELECTMODE);
                HANDLE_CASE_RETURN_STRING(ECMD_TOGGLE_OVERTYPE_MODE);
                HANDLE_CASE_RETURN_STRING(ECMD_CUT);
                HANDLE_CASE_RETURN_STRING(ECMD_COPY);
                HANDLE_CASE_RETURN_STRING(ECMD_PASTE);
                HANDLE_CASE_RETURN_STRING(ECMD_CUTLINE);
                HANDLE_CASE_RETURN_STRING(ECMD_DELETELINE);
                HANDLE_CASE_RETURN_STRING(ECMD_DELETEBLANKLINES);
                HANDLE_CASE_RETURN_STRING(ECMD_DELETEWHITESPACE);
                HANDLE_CASE_RETURN_STRING(ECMD_DELETETOEOL);
                HANDLE_CASE_RETURN_STRING(ECMD_DELETETOBOL);
                HANDLE_CASE_RETURN_STRING(ECMD_OPENLINEABOVE);
                HANDLE_CASE_RETURN_STRING(ECMD_OPENLINEBELOW);
                HANDLE_CASE_RETURN_STRING(ECMD_INDENT);
                HANDLE_CASE_RETURN_STRING(ECMD_UNINDENT);
                HANDLE_CASE_RETURN_STRING(ECMD_UNDO);
                HANDLE_CASE_RETURN_STRING(ECMD_UNDONOMOVE);
                HANDLE_CASE_RETURN_STRING(ECMD_REDO);
                HANDLE_CASE_RETURN_STRING(ECMD_REDONOMOVE);
                HANDLE_CASE_RETURN_STRING(ECMD_DELETEALLTEMPBOOKMARKS);
                HANDLE_CASE_RETURN_STRING(ECMD_TOGGLETEMPBOOKMARK);
                HANDLE_CASE_RETURN_STRING(ECMD_GOTONEXTBOOKMARK);
                HANDLE_CASE_RETURN_STRING(ECMD_GOTOPREVBOOKMARK);
                HANDLE_CASE_RETURN_STRING(ECMD_FIND);
                HANDLE_CASE_RETURN_STRING(ECMD_REPLACE);
                HANDLE_CASE_RETURN_STRING(ECMD_REPLACE_ALL);
                HANDLE_CASE_RETURN_STRING(ECMD_FINDNEXT);
                HANDLE_CASE_RETURN_STRING(ECMD_FINDNEXTWORD);
                HANDLE_CASE_RETURN_STRING(ECMD_FINDPREV);
                HANDLE_CASE_RETURN_STRING(ECMD_FINDPREVWORD);
                HANDLE_CASE_RETURN_STRING(ECMD_FINDAGAIN);
                HANDLE_CASE_RETURN_STRING(ECMD_TRANSPOSECHAR);
                HANDLE_CASE_RETURN_STRING(ECMD_TRANSPOSEWORD);
                HANDLE_CASE_RETURN_STRING(ECMD_TRANSPOSELINE);
                HANDLE_CASE_RETURN_STRING(ECMD_SELECTCURRENTWORD);
                HANDLE_CASE_RETURN_STRING(ECMD_DELETEWORDRIGHT);
                HANDLE_CASE_RETURN_STRING(ECMD_DELETEWORDLEFT);
                HANDLE_CASE_RETURN_STRING(ECMD_WORDPREV);
                HANDLE_CASE_RETURN_STRING(ECMD_WORDPREV_EXT);
                HANDLE_CASE_RETURN_STRING(ECMD_WORDNEXT);
                HANDLE_CASE_RETURN_STRING(ECMD_WORDNEXT_EXT);
                HANDLE_CASE_RETURN_STRING(ECMD_COMMENTBLOCK);
                HANDLE_CASE_RETURN_STRING(ECMD_UNCOMMENTBLOCK);
                HANDLE_CASE_RETURN_STRING(ECMD_SETREPEATCOUNT);
                HANDLE_CASE_RETURN_STRING(ECMD_WIDGETMARGIN_LBTNDOWN);
                HANDLE_CASE_RETURN_STRING(ECMD_SHOWCONTEXTMENU);
                HANDLE_CASE_RETURN_STRING(ECMD_CANCEL);
                HANDLE_CASE_RETURN_STRING(ECMD_PARAMINFO);
                HANDLE_CASE_RETURN_STRING(ECMD_TOGGLEVISSPACE);
                HANDLE_CASE_RETURN_STRING(ECMD_TOGGLECARETPASTEPOS);
                HANDLE_CASE_RETURN_STRING(ECMD_COMPLETEWORD);
                HANDLE_CASE_RETURN_STRING(ECMD_SHOWMEMBERLIST);
                HANDLE_CASE_RETURN_STRING(ECMD_FIRSTNONWHITEPREV);
                HANDLE_CASE_RETURN_STRING(ECMD_FIRSTNONWHITENEXT);
                HANDLE_CASE_RETURN_STRING(ECMD_HELPKEYWORD);
                HANDLE_CASE_RETURN_STRING(ECMD_FORMATSELECTION);
                HANDLE_CASE_RETURN_STRING(ECMD_OPENURL);
                HANDLE_CASE_RETURN_STRING(ECMD_INSERTFILE);
                HANDLE_CASE_RETURN_STRING(ECMD_TOGGLESHORTCUT);
                HANDLE_CASE_RETURN_STRING(ECMD_QUICKINFO);
                HANDLE_CASE_RETURN_STRING(ECMD_LEFT_EXT_COL);
                HANDLE_CASE_RETURN_STRING(ECMD_RIGHT_EXT_COL);
                HANDLE_CASE_RETURN_STRING(ECMD_UP_EXT_COL);
                HANDLE_CASE_RETURN_STRING(ECMD_DOWN_EXT_COL);
                HANDLE_CASE_RETURN_STRING(ECMD_TOGGLEWORDWRAP);
                HANDLE_CASE_RETURN_STRING(ECMD_ISEARCH);
                HANDLE_CASE_RETURN_STRING(ECMD_ISEARCHBACK);
                HANDLE_CASE_RETURN_STRING(ECMD_BOL_EXT_COL);
                HANDLE_CASE_RETURN_STRING(ECMD_EOL_EXT_COL);
                HANDLE_CASE_RETURN_STRING(ECMD_WORDPREV_EXT_COL);
                HANDLE_CASE_RETURN_STRING(ECMD_WORDNEXT_EXT_COL);
                HANDLE_CASE_RETURN_STRING(ECMD_OUTLN_HIDE_SELECTION);
                HANDLE_CASE_RETURN_STRING(ECMD_OUTLN_TOGGLE_CURRENT);
                HANDLE_CASE_RETURN_STRING(ECMD_OUTLN_TOGGLE_ALL);
                HANDLE_CASE_RETURN_STRING(ECMD_OUTLN_STOP_HIDING_ALL);
                HANDLE_CASE_RETURN_STRING(ECMD_OUTLN_STOP_HIDING_CURRENT);
                HANDLE_CASE_RETURN_STRING(ECMD_OUTLN_COLLAPSE_TO_DEF);
                HANDLE_CASE_RETURN_STRING(ECMD_DOUBLECLICK);
                HANDLE_CASE_RETURN_STRING(ECMD_EXTERNALLY_HANDLED_WIDGET_CLICK);
                HANDLE_CASE_RETURN_STRING(ECMD_COMMENT_BLOCK);
                HANDLE_CASE_RETURN_STRING(ECMD_UNCOMMENT_BLOCK);
                HANDLE_CASE_RETURN_STRING(ECMD_OPENFILE);
                HANDLE_CASE_RETURN_STRING(ECMD_NAVIGATETOURL);

                // For editor internal use only
                HANDLE_CASE_RETURN_STRING(ECMD_HANDLEIMEMESSAGE);
                HANDLE_CASE_RETURN_STRING(ECMD_SELTOGOBACK);
                HANDLE_CASE_RETURN_STRING(ECMD_COMPLETION_HIDE_ADVANCED);

                HANDLE_CASE_RETURN_STRING(ECMD_FORMATDOCUMENT);
                HANDLE_CASE_RETURN_STRING(ECMD_OUTLN_START_AUTOHIDING);
                HANDLE_CASE_RETURN_STRING(ECMD_INCREASEFILTER);
                HANDLE_CASE_RETURN_STRING(ECMD_DECREASEFILTER);
                HANDLE_CASE_RETURN_STRING(ECMD_SMARTTASKS);
                HANDLE_CASE_RETURN_STRING(ECMD_COPYTIP);
                HANDLE_CASE_RETURN_STRING(ECMD_PASTETIP);
                HANDLE_CASE_RETURN_STRING(ECMD_LEFTCLICK);
                HANDLE_CASE_RETURN_STRING(ECMD_GOTONEXTBOOKMARKINDOC);
                HANDLE_CASE_RETURN_STRING(ECMD_GOTOPREVBOOKMARKINDOC);
                HANDLE_CASE_RETURN_STRING(ECMD_INVOKESNIPPETFROMSHORTCUT);

                // For managed language services internal use only (clovett)
                HANDLE_CASE_RETURN_STRING(ECMD_AUTOCOMPLETE);
                HANDLE_CASE_RETURN_STRING(ECMD_INVOKESNIPPETPICKER2);
                HANDLE_CASE_RETURN_STRING(ECMD_DELETEALLBOOKMARKSINDOC);
                HANDLE_CASE_RETURN_STRING(ECMD_CONVERTTABSTOSPACES);
                HANDLE_CASE_RETURN_STRING(ECMD_CONVERTSPACESTOTABS);

                // Last Standard Editor Command (+1)
                HANDLE_CASE_RETURN_STRING(ECMD_FINAL);

                // Some new commands created during CTC file rationalisation
                HANDLE_CASE_RETURN_STRING(ECMD_STOP);
                HANDLE_CASE_RETURN_STRING(ECMD_REVERSECANCEL);
                HANDLE_CASE_RETURN_STRING(ECMD_SLNREFRESH);
                HANDLE_CASE_RETURN_STRING(ECMD_SAVECOPYOFITEMAS);

                // Shareable commands originating in the HTML editor
                // Shared table commands are obsolete! If you still rely on them, please contact jbresler or mikhaila on
                // the HTML editor team
                HANDLE_CASE_RETURN_STRING(ECMD_NEWELEMENT);
                HANDLE_CASE_RETURN_STRING(ECMD_NEWATTRIBUTE);
                HANDLE_CASE_RETURN_STRING(ECMD_NEWCOMPLEXTYPE);
                HANDLE_CASE_RETURN_STRING(ECMD_NEWSIMPLETYPE);
                HANDLE_CASE_RETURN_STRING(ECMD_NEWGROUP);
                HANDLE_CASE_RETURN_STRING(ECMD_NEWATTRIBUTEGROUP);
                HANDLE_CASE_RETURN_STRING(ECMD_NEWKEY);
                HANDLE_CASE_RETURN_STRING(ECMD_NEWRELATION);
                HANDLE_CASE_RETURN_STRING(ECMD_EDITKEY);
                HANDLE_CASE_RETURN_STRING(ECMD_EDITRELATION);
                HANDLE_CASE_RETURN_STRING(ECMD_MAKETYPEGLOBAL);
                HANDLE_CASE_RETURN_STRING(ECMD_PREVIEWDATASET);
                HANDLE_CASE_RETURN_STRING(ECMD_GENERATEDATASET);
                HANDLE_CASE_RETURN_STRING(ECMD_CREATESCHEMA);
                HANDLE_CASE_RETURN_STRING(ECMD_LAYOUTINDENT);
                HANDLE_CASE_RETURN_STRING(ECMD_LAYOUTUNINDENT);
                HANDLE_CASE_RETURN_STRING(ECMD_REMOVEHANDLER);
                HANDLE_CASE_RETURN_STRING(ECMD_EDITHANDLER);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDHANDLER);
                HANDLE_CASE_RETURN_STRING(ECMD_FONTSTYLE);
                HANDLE_CASE_RETURN_STRING(ECMD_FONTSTYLEGETLIST);
                HANDLE_CASE_RETURN_STRING(ECMD_PASTEASHTML);
                HANDLE_CASE_RETURN_STRING(ECMD_VIEWBORDERS);
                HANDLE_CASE_RETURN_STRING(ECMD_VIEWDETAILS);
                HANDLE_CASE_RETURN_STRING(ECMD_INSERTTABLE);
                HANDLE_CASE_RETURN_STRING(ECMD_INSERTCOLLEFT);
                HANDLE_CASE_RETURN_STRING(ECMD_INSERTCOLRIGHT);
                HANDLE_CASE_RETURN_STRING(ECMD_INSERTROWABOVE);
                HANDLE_CASE_RETURN_STRING(ECMD_INSERTROWBELOW);
                HANDLE_CASE_RETURN_STRING(ECMD_DELETETABLE);
                HANDLE_CASE_RETURN_STRING(ECMD_DELETECOLS);
                HANDLE_CASE_RETURN_STRING(ECMD_DELETEROWS);
                HANDLE_CASE_RETURN_STRING(ECMD_SELECTTABLE);
                HANDLE_CASE_RETURN_STRING(ECMD_SELECTTABLECOL);
                HANDLE_CASE_RETURN_STRING(ECMD_SELECTTABLEROW);
                HANDLE_CASE_RETURN_STRING(ECMD_SELECTTABLECELL);
                HANDLE_CASE_RETURN_STRING(ECMD_MERGECELLS);
                HANDLE_CASE_RETURN_STRING(ECMD_SPLITCELL);
                HANDLE_CASE_RETURN_STRING(ECMD_INSERTCELLLEFT);
                HANDLE_CASE_RETURN_STRING(ECMD_DELETECELLS);
                HANDLE_CASE_RETURN_STRING(ECMD_SHOWGRID);
                HANDLE_CASE_RETURN_STRING(ECMD_SNAPTOGRID);
                HANDLE_CASE_RETURN_STRING(ECMD_BOOKMARK);
                HANDLE_CASE_RETURN_STRING(ECMD_HYPERLINK);

                HANDLE_CASE_RETURN_STRING(ECMD_BULLETEDLIST);
                HANDLE_CASE_RETURN_STRING(ECMD_NUMBEREDLIST);
                HANDLE_CASE_RETURN_STRING(ECMD_EDITSCRIPT);
                HANDLE_CASE_RETURN_STRING(ECMD_EDITCODEBEHIND);
                HANDLE_CASE_RETURN_STRING(ECMD_DOCOUTLINEHTML);

                HANDLE_CASE_RETURN_STRING(ECMD_RUNATSERVER);
                HANDLE_CASE_RETURN_STRING(ECMD_WEBFORMSVERBS);
                HANDLE_CASE_RETURN_STRING(ECMD_WEBFORMSTEMPLATES);
                HANDLE_CASE_RETURN_STRING(ECMD_ENDTEMPLATE);
                HANDLE_CASE_RETURN_STRING(ECMD_EDITDEFAULTEVENT);
                HANDLE_CASE_RETURN_STRING(ECMD_SUPERSCRIPT);
                HANDLE_CASE_RETURN_STRING(ECMD_SUBSCRIPT);
                HANDLE_CASE_RETURN_STRING(ECMD_EDITSTYLE);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDIMAGEHEIGHTWIDTH);
                HANDLE_CASE_RETURN_STRING(ECMD_REMOVEIMAGEHEIGHTWIDTH);
                HANDLE_CASE_RETURN_STRING(ECMD_LOCKELEMENT);
                HANDLE_CASE_RETURN_STRING(ECMD_AUTOCLOSEOVERRIDE);
                HANDLE_CASE_RETURN_STRING(ECMD_NEWANY);
                HANDLE_CASE_RETURN_STRING(ECMD_NEWANYATTRIBUTE);
                HANDLE_CASE_RETURN_STRING(ECMD_DELETEKEY);
                HANDLE_CASE_RETURN_STRING(ECMD_AUTOARRANGE);
                HANDLE_CASE_RETURN_STRING(ECMD_VALIDATESCHEMA);
                HANDLE_CASE_RETURN_STRING(ECMD_NEWFACET);
                HANDLE_CASE_RETURN_STRING(ECMD_VALIDATEXMLDATA);
                HANDLE_CASE_RETURN_STRING(ECMD_DOCOUTLINETOGGLE);
                HANDLE_CASE_RETURN_STRING(ECMD_VALIDATEHTMLDATA);
                HANDLE_CASE_RETURN_STRING(ECMD_VIEWXMLSCHEMAOVERVIEW);
                HANDLE_CASE_RETURN_STRING(ECMD_SHOWDEFAULTVIEW);
                HANDLE_CASE_RETURN_STRING(ECMD_EXPAND_CHILDREN);
                HANDLE_CASE_RETURN_STRING(ECMD_COLLAPSE_CHILDREN);
                HANDLE_CASE_RETURN_STRING(ECMD_TOPDOWNLAYOUT);
                HANDLE_CASE_RETURN_STRING(ECMD_LEFTRIGHTLAYOUT);
                HANDLE_CASE_RETURN_STRING(ECMD_INSERTCELLRIGHT);
                HANDLE_CASE_RETURN_STRING(ECMD_EDITMASTER);
                HANDLE_CASE_RETURN_STRING(ECMD_INSERTSNIPPET);
                HANDLE_CASE_RETURN_STRING(ECMD_FORMATANDVALIDATION);
                HANDLE_CASE_RETURN_STRING(ECMD_COLLAPSETAG);
                HANDLE_CASE_RETURN_STRING(ECMD_SELECT_TAG);
                HANDLE_CASE_RETURN_STRING(ECMD_SELECT_TAG_CONTENT);
                HANDLE_CASE_RETURN_STRING(ECMD_CHECK_ACCESSIBILITY);
                HANDLE_CASE_RETURN_STRING(ECMD_UNCOLLAPSETAG);
                HANDLE_CASE_RETURN_STRING(ECMD_GENERATEPAGERESOURCE);
                HANDLE_CASE_RETURN_STRING(ECMD_SHOWNONVISUALCONTROLS);
                HANDLE_CASE_RETURN_STRING(ECMD_RESIZECOLUMN);
                HANDLE_CASE_RETURN_STRING(ECMD_RESIZEROW);
                HANDLE_CASE_RETURN_STRING(ECMD_MAKEABSOLUTE);
                HANDLE_CASE_RETURN_STRING(ECMD_MAKERELATIVE);
                HANDLE_CASE_RETURN_STRING(ECMD_MAKESTATIC);
                HANDLE_CASE_RETURN_STRING(ECMD_INSERTLAYER);
                HANDLE_CASE_RETURN_STRING(ECMD_UPDATEDESIGNVIEW);
                HANDLE_CASE_RETURN_STRING(ECMD_UPDATESOURCEVIEW);
                HANDLE_CASE_RETURN_STRING(ECMD_INSERTCAPTION);
                HANDLE_CASE_RETURN_STRING(ECMD_DELETECAPTION);
                HANDLE_CASE_RETURN_STRING(ECMD_MAKEPOSITIONNOTSET);
                HANDLE_CASE_RETURN_STRING(ECMD_AUTOPOSITIONOPTIONS);
                HANDLE_CASE_RETURN_STRING(ECMD_EDITIMAGE);

                HANDLE_CASE_RETURN_STRING(ECMD_VALIDATION_TARGET);
                HANDLE_CASE_RETURN_STRING(ECMD_VALIDATION_TARGET_GET_LIST);
                HANDLE_CASE_RETURN_STRING(ECMD_CSS_TARGET);
                HANDLE_CASE_RETURN_STRING(ECMD_CSS_TARGET_GET_LIST);

                HANDLE_CASE_RETURN_STRING(ECMD_COMPILE);
                HANDLE_CASE_RETURN_STRING(ECMD_PROJSETTINGS);
                HANDLE_CASE_RETURN_STRING(ECMD_LINKONLY);
                HANDLE_CASE_RETURN_STRING(ECMD_REMOVE);
                HANDLE_CASE_RETURN_STRING(ECMD_PROJSTARTDEBUG);
                HANDLE_CASE_RETURN_STRING(ECMD_PROJSTEPINTO);
                HANDLE_CASE_RETURN_STRING(ECMD_UPDATEMGDRES);
                HANDLE_CASE_RETURN_STRING(ECMD_UPDATEWEBREF);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDRESOURCE);
                HANDLE_CASE_RETURN_STRING(ECMD_WEBDEPLOY);
                HANDLE_CASE_RETURN_STRING(ECMD_PROJTOOLORDER);
                HANDLE_CASE_RETURN_STRING(ECMD_PROJECTTOOLFILES);
                HANDLE_CASE_RETURN_STRING(ECMD_OTB_PGO_INSTRUMENT);
                HANDLE_CASE_RETURN_STRING(ECMD_OTB_PGO_OPT);
                HANDLE_CASE_RETURN_STRING(ECMD_OTB_PGO_UPDATE);
                HANDLE_CASE_RETURN_STRING(ECMD_OTB_PGO_RUNSCENARIO);

                // Shareable commands originating in the VB and VBA projects
                HANDLE_CASE_RETURN_STRING(ECMD_ADDHTMLPAGE);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDHTMLPAGECTX);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDMODULE);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDMODULECTX);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDWFCFORM);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDWEBFORM);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDMASTERPAGE);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDUSERCONTROL);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDCONTENTPAGE);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDIMAGEGENERATOR);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDINHERWFCFORM);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDINHERCONTROL);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDWEBUSERCONTROL);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDTBXCOMPONENT);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDWEBSERVICE);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDSTYLESHEET);
                HANDLE_CASE_RETURN_STRING(ECMD_SETBROWSELOCATION);
                HANDLE_CASE_RETURN_STRING(ECMD_REFRESHFOLDER);
                HANDLE_CASE_RETURN_STRING(ECMD_SETBROWSELOCATIONCTX);
                HANDLE_CASE_RETURN_STRING(ECMD_VIEWMARKUP);
                HANDLE_CASE_RETURN_STRING(ECMD_NEXTMETHOD);
                HANDLE_CASE_RETURN_STRING(ECMD_PREVMETHOD);

                // VB refactoring commands
                HANDLE_CASE_RETURN_STRING(ECMD_RENAMESYMBOL);
                HANDLE_CASE_RETURN_STRING(ECMD_SHOWREFERENCES);
                HANDLE_CASE_RETURN_STRING(ECMD_CREATESNIPPET);
                HANDLE_CASE_RETURN_STRING(ECMD_CREATEREPLACEMENT);
                HANDLE_CASE_RETURN_STRING(ECMD_INSERTCOMMENT);
                HANDLE_CASE_RETURN_STRING(ECMD_VIEWCOMPONENTDESIGNER);
                HANDLE_CASE_RETURN_STRING(ECMD_GOTOTYPEDEF);
                HANDLE_CASE_RETURN_STRING(ECMD_SHOWSNIPPETHIGHLIGHTING);
                HANDLE_CASE_RETURN_STRING(ECMD_HIDESNIPPETHIGHLIGHTING);

                // Shareable commands originating in the VFP project
                HANDLE_CASE_RETURN_STRING(ECMD_ADDVFPPAGE);
                HANDLE_CASE_RETURN_STRING(ECMD_SETBREAKPOINT);

                // Shareable commands originating in the HELP WORKSHOP project
                HANDLE_CASE_RETURN_STRING(ECMD_SHOWALLFILES);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDTOPROJECT);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDBLANKNODE);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDNODEFROMFILE);
                HANDLE_CASE_RETURN_STRING(ECMD_CHANGEURLFROMFILE);
                HANDLE_CASE_RETURN_STRING(ECMD_EDITTOPIC);
                HANDLE_CASE_RETURN_STRING(ECMD_EDITTITLE);
                HANDLE_CASE_RETURN_STRING(ECMD_MOVENODEUP);
                HANDLE_CASE_RETURN_STRING(ECMD_MOVENODEDOWN);
                HANDLE_CASE_RETURN_STRING(ECMD_MOVENODELEFT);
                HANDLE_CASE_RETURN_STRING(ECMD_MOVENODERIGHT);

                // Shareable commands originating in the Deploy project
                HANDLE_CASE_RETURN_STRING(ECMD_ADDOUTPUT);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDFILE);
                HANDLE_CASE_RETURN_STRING(ECMD_MERGEMODULE);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDCOMPONENTS);
                HANDLE_CASE_RETURN_STRING(ECMD_LAUNCHINSTALLER);
                HANDLE_CASE_RETURN_STRING(ECMD_LAUNCHUNINSTALL);
                HANDLE_CASE_RETURN_STRING(ECMD_LAUNCHORCA);
                HANDLE_CASE_RETURN_STRING(ECMD_FILESYSTEMEDITOR);
                HANDLE_CASE_RETURN_STRING(ECMD_REGISTRYEDITOR);
                HANDLE_CASE_RETURN_STRING(ECMD_FILETYPESEDITOR);
                HANDLE_CASE_RETURN_STRING(ECMD_USERINTERFACEEDITOR);
                HANDLE_CASE_RETURN_STRING(ECMD_CUSTOMACTIONSEDITOR);
                HANDLE_CASE_RETURN_STRING(ECMD_LAUNCHCONDITIONSEDITOR);
                HANDLE_CASE_RETURN_STRING(ECMD_EDITOR);
                HANDLE_CASE_RETURN_STRING(ECMD_EXCLUDE);
                HANDLE_CASE_RETURN_STRING(ECMD_REFRESHDEPENDENCIES);
                HANDLE_CASE_RETURN_STRING(ECMD_VIEWOUTPUTS);
                HANDLE_CASE_RETURN_STRING(ECMD_VIEWDEPENDENCIES);
                HANDLE_CASE_RETURN_STRING(ECMD_VIEWFILTER);
                HANDLE_CASE_RETURN_STRING(ECMD_KEY);
                HANDLE_CASE_RETURN_STRING(ECMD_STRING);
                HANDLE_CASE_RETURN_STRING(ECMD_BINARY);
                HANDLE_CASE_RETURN_STRING(ECMD_DWORD);
                HANDLE_CASE_RETURN_STRING(ECMD_KEYSOLO);
                HANDLE_CASE_RETURN_STRING(ECMD_IMPORT);
                HANDLE_CASE_RETURN_STRING(ECMD_FOLDER);
                HANDLE_CASE_RETURN_STRING(ECMD_PROJECTOUTPUT);
                HANDLE_CASE_RETURN_STRING(ECMD_FILE);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDMERGEMODULES);
                HANDLE_CASE_RETURN_STRING(ECMD_CREATESHORTCUT);
                HANDLE_CASE_RETURN_STRING(ECMD_LARGEICONS);
                HANDLE_CASE_RETURN_STRING(ECMD_SMALLICONS);
                HANDLE_CASE_RETURN_STRING(ECMD_LIST);
                HANDLE_CASE_RETURN_STRING(ECMD_DETAILS);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDFILETYPE);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDACTION);
                HANDLE_CASE_RETURN_STRING(ECMD_SETASDEFAULT);
                HANDLE_CASE_RETURN_STRING(ECMD_MOVEUP);
                HANDLE_CASE_RETURN_STRING(ECMD_MOVEDOWN);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDDIALOG);
                HANDLE_CASE_RETURN_STRING(ECMD_IMPORTDIALOG);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDFILESEARCH);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDREGISTRYSEARCH);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDCOMPONENTSEARCH);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDLAUNCHCONDITION);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDCUSTOMACTION);
                HANDLE_CASE_RETURN_STRING(ECMD_OUTPUTS);
                HANDLE_CASE_RETURN_STRING(ECMD_DEPENDENCIES);
                HANDLE_CASE_RETURN_STRING(ECMD_FILTER);
                HANDLE_CASE_RETURN_STRING(ECMD_COMPONENTS);
                HANDLE_CASE_RETURN_STRING(ECMD_ENVSTRING);
                HANDLE_CASE_RETURN_STRING(ECMD_CREATEEMPTYSHORTCUT);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDFILECONDITION);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDREGISTRYCONDITION);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDCOMPONENTCONDITION);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDURTCONDITION);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDIISCONDITION);


                HANDLE_CASE_RETURN_STRING(ECMD_USERSAPPLICATIONDATAFOLDER); // ECMD_SPECIALFOLDERBASE
                HANDLE_CASE_RETURN_STRING(ECMD_COMMONFILES64FOLDER);
                HANDLE_CASE_RETURN_STRING(ECMD_COMMONFILESFOLDER);
                HANDLE_CASE_RETURN_STRING(ECMD_CUSTOMFOLDER);
                HANDLE_CASE_RETURN_STRING(ECMD_USERSDESKTOP);
                HANDLE_CASE_RETURN_STRING(ECMD_USERSFAVORITESFOLDER);
                HANDLE_CASE_RETURN_STRING(ECMD_FONTSFOLDER);
                HANDLE_CASE_RETURN_STRING(ECMD_GLOBALASSEMBLYCACHEFOLDER);
                HANDLE_CASE_RETURN_STRING(ECMD_MODULERETARGETABLEFOLDER);
                HANDLE_CASE_RETURN_STRING(ECMD_USERSPERSONALDATAFOLDER);
                HANDLE_CASE_RETURN_STRING(ECMD_PROGRAMFILES64FOLDER);
                HANDLE_CASE_RETURN_STRING(ECMD_PROGRAMFILESFOLDER);
                HANDLE_CASE_RETURN_STRING(ECMD_USERSPROGRAMSMENU);
                HANDLE_CASE_RETURN_STRING(ECMD_USERSSENDTOMENU);
                HANDLE_CASE_RETURN_STRING(ECMD_SHAREDCOMPONENTSFOLDER);
                HANDLE_CASE_RETURN_STRING(ECMD_USERSSTARTMENU);
                HANDLE_CASE_RETURN_STRING(ECMD_USERSSTARTUPFOLDER);
                HANDLE_CASE_RETURN_STRING(ECMD_SYSTEM64FOLDER);
                HANDLE_CASE_RETURN_STRING(ECMD_SYSTEMFOLDER);
                HANDLE_CASE_RETURN_STRING(ECMD_APPLICATIONFOLDER);
                HANDLE_CASE_RETURN_STRING(ECMD_USERSTEMPLATEFOLDER);
                HANDLE_CASE_RETURN_STRING(ECMD_WEBCUSTOMFOLDER);
                HANDLE_CASE_RETURN_STRING(ECMD_WINDOWSFOLDER);      //ECMD_SPECIALFOLDERLAST

                // Shareable commands originating in the Visual Studio Analyzer project
                HANDLE_CASE_RETURN_STRING(ECMD_EXPORTEVENTS);
                HANDLE_CASE_RETURN_STRING(ECMD_IMPORTEVENTS);
                HANDLE_CASE_RETURN_STRING(ECMD_VIEWEVENT);
                HANDLE_CASE_RETURN_STRING(ECMD_VIEWEVENTLIST);
                HANDLE_CASE_RETURN_STRING(ECMD_VIEWCHART);
                HANDLE_CASE_RETURN_STRING(ECMD_VIEWMACHINEDIAGRAM);
                HANDLE_CASE_RETURN_STRING(ECMD_VIEWPROCESSDIAGRAM);
                HANDLE_CASE_RETURN_STRING(ECMD_VIEWSOURCEDIAGRAM);
                HANDLE_CASE_RETURN_STRING(ECMD_VIEWSTRUCTUREDIAGRAM);
                HANDLE_CASE_RETURN_STRING(ECMD_VIEWTIMELINE);
                HANDLE_CASE_RETURN_STRING(ECMD_VIEWSUMMARY);
                HANDLE_CASE_RETURN_STRING(ECMD_APPLYFILTER);
                HANDLE_CASE_RETURN_STRING(ECMD_CLEARFILTER);
                HANDLE_CASE_RETURN_STRING(ECMD_STARTRECORDING);
                HANDLE_CASE_RETURN_STRING(ECMD_STOPRECORDING);
                HANDLE_CASE_RETURN_STRING(ECMD_PAUSERECORDING);
                HANDLE_CASE_RETURN_STRING(ECMD_ACTIVATEFILTER);
                HANDLE_CASE_RETURN_STRING(ECMD_SHOWFIRSTEVENT);
                HANDLE_CASE_RETURN_STRING(ECMD_SHOWPREVIOUSEVENT);
                HANDLE_CASE_RETURN_STRING(ECMD_SHOWNEXTEVENT);
                HANDLE_CASE_RETURN_STRING(ECMD_SHOWLASTEVENT);
                HANDLE_CASE_RETURN_STRING(ECMD_REPLAYEVENTS);
                HANDLE_CASE_RETURN_STRING(ECMD_STOPREPLAY);
                HANDLE_CASE_RETURN_STRING(ECMD_INCREASEPLAYBACKSPEED);
                HANDLE_CASE_RETURN_STRING(ECMD_DECREASEPLAYBACKSPEED);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDMACHINE);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDREMOVECOLUMNS);
                HANDLE_CASE_RETURN_STRING(ECMD_SORTCOLUMNS);
                HANDLE_CASE_RETURN_STRING(ECMD_SAVECOLUMNSETTINGS);
                HANDLE_CASE_RETURN_STRING(ECMD_RESETCOLUMNSETTINGS);
                HANDLE_CASE_RETURN_STRING(ECMD_SIZECOLUMNSTOFIT);
                HANDLE_CASE_RETURN_STRING(ECMD_AUTOSELECT);
                HANDLE_CASE_RETURN_STRING(ECMD_AUTOFILTER);
                HANDLE_CASE_RETURN_STRING(ECMD_AUTOPLAYTRACK);
                HANDLE_CASE_RETURN_STRING(ECMD_GOTOEVENT);
                HANDLE_CASE_RETURN_STRING(ECMD_ZOOMTOFIT);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDGRAPH);
                HANDLE_CASE_RETURN_STRING(ECMD_REMOVEGRAPH);
                HANDLE_CASE_RETURN_STRING(ECMD_CONNECTMACHINE);
                HANDLE_CASE_RETURN_STRING(ECMD_DISCONNECTMACHINE);
                HANDLE_CASE_RETURN_STRING(ECMD_EXPANDSELECTION);
                HANDLE_CASE_RETURN_STRING(ECMD_COLLAPSESELECTION);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDFILTER);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDPREDEFINED0);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDPREDEFINED1);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDPREDEFINED2);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDPREDEFINED3);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDPREDEFINED4);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDPREDEFINED5);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDPREDEFINED6);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDPREDEFINED7);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDPREDEFINED8);
                HANDLE_CASE_RETURN_STRING(ECMD_TIMELINESIZETOFIT);

                // Shareable commands originating with Crystal Reports
                HANDLE_CASE_RETURN_STRING(ECMD_FIELDVIEW);
                HANDLE_CASE_RETURN_STRING(ECMD_SELECTEXPERT);
                HANDLE_CASE_RETURN_STRING(ECMD_TOPNEXPERT);
                HANDLE_CASE_RETURN_STRING(ECMD_SORTORDER);
                HANDLE_CASE_RETURN_STRING(ECMD_PROPPAGE);
                HANDLE_CASE_RETURN_STRING(ECMD_HELP);
                HANDLE_CASE_RETURN_STRING(ECMD_SAVEREPORT);
                HANDLE_CASE_RETURN_STRING(ECMD_INSERTSUMMARY);
                HANDLE_CASE_RETURN_STRING(ECMD_INSERTGROUP);
                HANDLE_CASE_RETURN_STRING(ECMD_INSERTSUBREPORT);
                HANDLE_CASE_RETURN_STRING(ECMD_INSERTCHART);
                HANDLE_CASE_RETURN_STRING(ECMD_INSERTPICTURE);

                // Shareable commands from the common project area (DirPrj)
                HANDLE_CASE_RETURN_STRING(ECMD_SETASSTARTPAGE);
                HANDLE_CASE_RETURN_STRING(ECMD_RECALCULATELINKS);
                HANDLE_CASE_RETURN_STRING(ECMD_WEBPERMISSIONS);
                HANDLE_CASE_RETURN_STRING(ECMD_COMPARETOMASTER);
                HANDLE_CASE_RETURN_STRING(ECMD_WORKOFFLINE);
                HANDLE_CASE_RETURN_STRING(ECMD_SYNCHRONIZEFOLDER);
                HANDLE_CASE_RETURN_STRING(ECMD_SYNCHRONIZEALLFOLDERS);
                HANDLE_CASE_RETURN_STRING(ECMD_COPYPROJECT);
                HANDLE_CASE_RETURN_STRING(ECMD_IMPORTFILEFROMWEB);
                HANDLE_CASE_RETURN_STRING(ECMD_INCLUDEINPROJECT);
                HANDLE_CASE_RETURN_STRING(ECMD_EXCLUDEFROMPROJECT);
                HANDLE_CASE_RETURN_STRING(ECMD_BROKENLINKSREPORT);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDPROJECTOUTPUTS);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDREFERENCE);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDWEBREFERENCE);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDWEBREFERENCECTX);
                HANDLE_CASE_RETURN_STRING(ECMD_UPDATEWEBREFERENCE);
                HANDLE_CASE_RETURN_STRING(ECMD_RUNCUSTOMTOOL);
                HANDLE_CASE_RETURN_STRING(ECMD_SETRUNTIMEVERSION);
                HANDLE_CASE_RETURN_STRING(ECMD_VIEWREFINOBJECTBROWSER);
                HANDLE_CASE_RETURN_STRING(ECMD_PUBLISH);
                HANDLE_CASE_RETURN_STRING(ECMD_PUBLISHCTX);
                HANDLE_CASE_RETURN_STRING(ECMD_STARTOPTIONS);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDREFERENCECTX);
                HANDLE_CASE_RETURN_STRING(ECMD_STARTOPTIONSCTX);
                HANDLE_CASE_RETURN_STRING(ECMD_DETACHLOCALDATAFILECTX);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDSERVICEREFERENCE);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDSERVICEREFERENCECTX);
                HANDLE_CASE_RETURN_STRING(ECMD_UPDATESERVICEREFERENCE);
                HANDLE_CASE_RETURN_STRING(ECMD_CONFIGURESERVICEREFERENCE);

                // Shareable commands for right drag operations
                HANDLE_CASE_RETURN_STRING(ECMD_DRAG_MOVE);
                HANDLE_CASE_RETURN_STRING(ECMD_DRAG_COPY);
                HANDLE_CASE_RETURN_STRING(ECMD_DRAG_CANCEL);

                // Shareable commands from the VC resource editor
                HANDLE_CASE_RETURN_STRING(ECMD_TESTDIALOG);
                HANDLE_CASE_RETURN_STRING(ECMD_SPACEACROSS);
                HANDLE_CASE_RETURN_STRING(ECMD_SPACEDOWN);
                HANDLE_CASE_RETURN_STRING(ECMD_TOGGLEGRID);
                HANDLE_CASE_RETURN_STRING(ECMD_TOGGLEGUIDES);
                HANDLE_CASE_RETURN_STRING(ECMD_SIZETOTEXT);
                HANDLE_CASE_RETURN_STRING(ECMD_CENTERVERT);
                HANDLE_CASE_RETURN_STRING(ECMD_CENTERHORZ);
                HANDLE_CASE_RETURN_STRING(ECMD_FLIPDIALOG);
                HANDLE_CASE_RETURN_STRING(ECMD_SETTABORDER);
                HANDLE_CASE_RETURN_STRING(ECMD_BUTTONRIGHT);
                HANDLE_CASE_RETURN_STRING(ECMD_BUTTONBOTTOM);
                HANDLE_CASE_RETURN_STRING(ECMD_AUTOLAYOUTGROW);
                HANDLE_CASE_RETURN_STRING(ECMD_AUTOLAYOUTNORESIZE);
                HANDLE_CASE_RETURN_STRING(ECMD_AUTOLAYOUTOPTIMIZE);
                HANDLE_CASE_RETURN_STRING(ECMD_GUIDESETTINGS);
                HANDLE_CASE_RETURN_STRING(ECMD_RESOURCEINCLUDES);
                HANDLE_CASE_RETURN_STRING(ECMD_RESOURCESYMBOLS);
                HANDLE_CASE_RETURN_STRING(ECMD_OPENBINARY);
                HANDLE_CASE_RETURN_STRING(ECMD_RESOURCEOPEN);
                HANDLE_CASE_RETURN_STRING(ECMD_RESOURCENEW);
                HANDLE_CASE_RETURN_STRING(ECMD_RESOURCENEWCOPY);
                HANDLE_CASE_RETURN_STRING(ECMD_INSERT);
                HANDLE_CASE_RETURN_STRING(ECMD_EXPORT);
                HANDLE_CASE_RETURN_STRING(ECMD_CTLMOVELEFT);
                HANDLE_CASE_RETURN_STRING(ECMD_CTLMOVEDOWN);
                HANDLE_CASE_RETURN_STRING(ECMD_CTLMOVERIGHT);
                HANDLE_CASE_RETURN_STRING(ECMD_CTLMOVEUP);
                HANDLE_CASE_RETURN_STRING(ECMD_CTLSIZEDOWN);
                HANDLE_CASE_RETURN_STRING(ECMD_CTLSIZEUP);
                HANDLE_CASE_RETURN_STRING(ECMD_CTLSIZELEFT);
                HANDLE_CASE_RETURN_STRING(ECMD_CTLSIZERIGHT);
                HANDLE_CASE_RETURN_STRING(ECMD_NEWACCELERATOR);
                HANDLE_CASE_RETURN_STRING(ECMD_CAPTUREKEYSTROKE);
                HANDLE_CASE_RETURN_STRING(ECMD_INSERTACTIVEXCTL);
                HANDLE_CASE_RETURN_STRING(ECMD_INVERTCOLORS);
                HANDLE_CASE_RETURN_STRING(ECMD_FLIPHORIZONTAL);
                HANDLE_CASE_RETURN_STRING(ECMD_FLIPVERTICAL);
                HANDLE_CASE_RETURN_STRING(ECMD_ROTATE90);
                HANDLE_CASE_RETURN_STRING(ECMD_SHOWCOLORSWINDOW);
                HANDLE_CASE_RETURN_STRING(ECMD_NEWSTRING);
                HANDLE_CASE_RETURN_STRING(ECMD_NEWINFOBLOCK);
                HANDLE_CASE_RETURN_STRING(ECMD_DELETEINFOBLOCK);
                HANDLE_CASE_RETURN_STRING(ECMD_ADJUSTCOLORS);
                HANDLE_CASE_RETURN_STRING(ECMD_LOADPALETTE);
                HANDLE_CASE_RETURN_STRING(ECMD_SAVEPALETTE);
                HANDLE_CASE_RETURN_STRING(ECMD_CHECKMNEMONICS);
                HANDLE_CASE_RETURN_STRING(ECMD_DRAWOPAQUE);
                HANDLE_CASE_RETURN_STRING(ECMD_TOOLBAREDITOR);
                HANDLE_CASE_RETURN_STRING(ECMD_GRIDSETTINGS);
                HANDLE_CASE_RETURN_STRING(ECMD_NEWDEVICEIMAGE);
                HANDLE_CASE_RETURN_STRING(ECMD_OPENDEVICEIMAGE);
                HANDLE_CASE_RETURN_STRING(ECMD_DELETEDEVICEIMAGE);
                HANDLE_CASE_RETURN_STRING(ECMD_VIEWASPOPUP);
                HANDLE_CASE_RETURN_STRING(ECMD_CHECKMENUMNEMONICS);
                HANDLE_CASE_RETURN_STRING(ECMD_SHOWIMAGEGRID);
                HANDLE_CASE_RETURN_STRING(ECMD_SHOWTILEGRID);
                HANDLE_CASE_RETURN_STRING(ECMD_MAGNIFY);
                HANDLE_CASE_RETURN_STRING(cmdidResProps);
                HANDLE_CASE_RETURN_STRING(ECMD_IMPORTICONIMAGE);
                HANDLE_CASE_RETURN_STRING(ECMD_EXPORTICONIMAGE);
                HANDLE_CASE_RETURN_STRING(ECMD_OPENEXTERNALEDITOR);

                // Shareable commands from the VC resource editor (Image editor toolbar)
                HANDLE_CASE_RETURN_STRING(ECMD_PICKRECTANGLE);
                HANDLE_CASE_RETURN_STRING(ECMD_PICKREGION);
                HANDLE_CASE_RETURN_STRING(ECMD_PICKCOLOR);
                HANDLE_CASE_RETURN_STRING(ECMD_ERASERTOOL);
                HANDLE_CASE_RETURN_STRING(ECMD_FILLTOOL);
                HANDLE_CASE_RETURN_STRING(ECMD_PENCILTOOL);
                HANDLE_CASE_RETURN_STRING(ECMD_BRUSHTOOL);
                HANDLE_CASE_RETURN_STRING(ECMD_AIRBRUSHTOOL);
                HANDLE_CASE_RETURN_STRING(ECMD_LINETOOL);
                HANDLE_CASE_RETURN_STRING(ECMD_CURVETOOL);
                HANDLE_CASE_RETURN_STRING(ECMD_TEXTTOOL);
                HANDLE_CASE_RETURN_STRING(ECMD_RECTTOOL);
                HANDLE_CASE_RETURN_STRING(ECMD_OUTLINERECTTOOL);
                HANDLE_CASE_RETURN_STRING(ECMD_FILLEDRECTTOOL);
                HANDLE_CASE_RETURN_STRING(ECMD_ROUNDRECTTOOL);
                HANDLE_CASE_RETURN_STRING(ECMD_OUTLINEROUNDRECTTOOL);
                HANDLE_CASE_RETURN_STRING(ECMD_FILLEDROUNDRECTTOOL);
                HANDLE_CASE_RETURN_STRING(ECMD_ELLIPSETOOL);
                HANDLE_CASE_RETURN_STRING(ECMD_OUTLINEELLIPSETOOL);
                HANDLE_CASE_RETURN_STRING(ECMD_FILLEDELLIPSETOOL);
                HANDLE_CASE_RETURN_STRING(ECMD_SETHOTSPOT);
                HANDLE_CASE_RETURN_STRING(ECMD_ZOOMTOOL);
                HANDLE_CASE_RETURN_STRING(ECMD_ZOOM1X);
                HANDLE_CASE_RETURN_STRING(ECMD_ZOOM2X);
                HANDLE_CASE_RETURN_STRING(ECMD_ZOOM6X);
                HANDLE_CASE_RETURN_STRING(ECMD_ZOOM8X);
                HANDLE_CASE_RETURN_STRING(ECMD_TRANSPARENTBCKGRND);
                HANDLE_CASE_RETURN_STRING(ECMD_OPAQUEBCKGRND);

                HANDLE_CASE_RETURN_STRING(ECMD_ERASERSMALL);
                HANDLE_CASE_RETURN_STRING(ECMD_ERASERMEDIUM);
                HANDLE_CASE_RETURN_STRING(ECMD_ERASERLARGE);
                HANDLE_CASE_RETURN_STRING(ECMD_ERASERLARGER);
                HANDLE_CASE_RETURN_STRING(ECMD_CIRCLELARGE);
                HANDLE_CASE_RETURN_STRING(ECMD_CIRCLEMEDIUM);
                HANDLE_CASE_RETURN_STRING(ECMD_CIRCLESMALL);
                HANDLE_CASE_RETURN_STRING(ECMD_SQUARELARGE);
                HANDLE_CASE_RETURN_STRING(ECMD_SQUAREMEDIUM);
                HANDLE_CASE_RETURN_STRING(ECMD_SQUARESMALL);
                HANDLE_CASE_RETURN_STRING(ECMD_LEFTDIAGLARGE);
                HANDLE_CASE_RETURN_STRING(ECMD_LEFTDIAGMEDIUM);
                HANDLE_CASE_RETURN_STRING(ECMD_LEFTDIAGSMALL);
                HANDLE_CASE_RETURN_STRING(ECMD_RIGHTDIAGLARGE);
                HANDLE_CASE_RETURN_STRING(ECMD_RIGHTDIAGMEDIUM);
                HANDLE_CASE_RETURN_STRING(ECMD_RIGHTDIAGSMALL);
                HANDLE_CASE_RETURN_STRING(ECMD_SPLASHSMALL);
                HANDLE_CASE_RETURN_STRING(ECMD_SPLASHMEDIUM);
                HANDLE_CASE_RETURN_STRING(ECMD_SPLASHLARGE);
                HANDLE_CASE_RETURN_STRING(ECMD_LINESMALLER);
                HANDLE_CASE_RETURN_STRING(ECMD_LINESMALL);
                HANDLE_CASE_RETURN_STRING(ECMD_LINEMEDIUM);
                HANDLE_CASE_RETURN_STRING(ECMD_LINELARGE);
                HANDLE_CASE_RETURN_STRING(ECMD_LINELARGER);
                HANDLE_CASE_RETURN_STRING(ECMD_LARGERBRUSH);
                HANDLE_CASE_RETURN_STRING(ECMD_LARGEBRUSH);
                HANDLE_CASE_RETURN_STRING(ECMD_STDBRUSH);
                HANDLE_CASE_RETURN_STRING(ECMD_SMALLBRUSH);
                HANDLE_CASE_RETURN_STRING(ECMD_SMALLERBRUSH);
                HANDLE_CASE_RETURN_STRING(ECMD_ZOOMIN);
                HANDLE_CASE_RETURN_STRING(ECMD_ZOOMOUT);
                HANDLE_CASE_RETURN_STRING(ECMD_PREVCOLOR);
                HANDLE_CASE_RETURN_STRING(ECMD_PREVECOLOR);
                HANDLE_CASE_RETURN_STRING(ECMD_NEXTCOLOR);
                HANDLE_CASE_RETURN_STRING(ECMD_NEXTECOLOR);
                HANDLE_CASE_RETURN_STRING(ECMD_IMG_OPTIONS);

                // Sharable Commands from Visual Web Developer (website projects)
                HANDLE_CASE_RETURN_STRING(ECMD_STARTWEBADMINTOOL);
                HANDLE_CASE_RETURN_STRING(ECMD_NESTRELATEDFILES);

                // Shareable commands from WINFORMS
                HANDLE_CASE_RETURN_STRING(ECMD_CANCELDRAG);
                HANDLE_CASE_RETURN_STRING(ECMD_DEFAULTACTION);
                HANDLE_CASE_RETURN_STRING(ECMD_CTLMOVEUPGRID);
                HANDLE_CASE_RETURN_STRING(ECMD_CTLMOVEDOWNGRID);
                HANDLE_CASE_RETURN_STRING(ECMD_CTLMOVELEFTGRID);
                HANDLE_CASE_RETURN_STRING(ECMD_CTLMOVERIGHTGRID);
                HANDLE_CASE_RETURN_STRING(ECMD_CTLSIZERIGHTGRID);
                HANDLE_CASE_RETURN_STRING(ECMD_CTLSIZEUPGRID);
                HANDLE_CASE_RETURN_STRING(ECMD_CTLSIZELEFTGRID);
                HANDLE_CASE_RETURN_STRING(ECMD_CTLSIZEDOWNGRID);
                HANDLE_CASE_RETURN_STRING(ECMD_NEXTCTL);
                HANDLE_CASE_RETURN_STRING(ECMD_PREVCTL);
                HANDLE_CASE_RETURN_STRING(ECMD_RENAME);
                HANDLE_CASE_RETURN_STRING(ECMD_EXTRACTMETHOD);
                HANDLE_CASE_RETURN_STRING(ECMD_ENCAPSULATEFIELD);
                HANDLE_CASE_RETURN_STRING(ECMD_EXTRACTINTERFACE);
                HANDLE_CASE_RETURN_STRING(ECMD_PROMOTELOCAL);
                HANDLE_CASE_RETURN_STRING(ECMD_REMOVEPARAMETERS);
                HANDLE_CASE_RETURN_STRING(ECMD_REORDERPARAMETERS);
                HANDLE_CASE_RETURN_STRING(ECMD_GENERATEMETHODSTUB);
                HANDLE_CASE_RETURN_STRING(ECMD_IMPLEMENTINTERFACEIMPLICIT);
                HANDLE_CASE_RETURN_STRING(ECMD_IMPLEMENTINTERFACEEXPLICIT);
                HANDLE_CASE_RETURN_STRING(ECMD_IMPLEMENTABSTRACTCLASS);
                HANDLE_CASE_RETURN_STRING(ECMD_SURROUNDWITH);

                // Additional shell commands added to CMDSETID_StandardCommandSet2K
                // because CLSID_StandardCommandSet97 is now considered closed.
                HANDLE_CASE_RETURN_STRING(cmdidToggleWordWrapOW);
                HANDLE_CASE_RETURN_STRING(cmdidGotoNextLocationOW);
                HANDLE_CASE_RETURN_STRING(cmdidGotoPrevLocationOW);
                HANDLE_CASE_RETURN_STRING(cmdidBuildOnlyProject);
                HANDLE_CASE_RETURN_STRING(cmdidRebuildOnlyProject);
                HANDLE_CASE_RETURN_STRING(cmdidCleanOnlyProject);
                HANDLE_CASE_RETURN_STRING(cmdidSetBuildStartupsOnlyOnRun);
                HANDLE_CASE_RETURN_STRING(cmdidUnhideAll);
                HANDLE_CASE_RETURN_STRING(cmdidHideFolder);
                HANDLE_CASE_RETURN_STRING(cmdidUnhideFolders);
                HANDLE_CASE_RETURN_STRING(cmdidCopyFullPathName);
                HANDLE_CASE_RETURN_STRING(cmdidSaveFolderAsSolution);
                HANDLE_CASE_RETURN_STRING(cmdidManageUserSettings);
                HANDLE_CASE_RETURN_STRING(cmdidNewSolutionFolder);
                HANDLE_CASE_RETURN_STRING(cmdidSetTrackSelInSlnExp);//changed to match VS 2005 cmdid
                HANDLE_CASE_RETURN_STRING(cmdidClearPaneOW);
                HANDLE_CASE_RETURN_STRING(cmdidGotoErrorTagOW);
                HANDLE_CASE_RETURN_STRING(cmdidGotoNextErrorTagOW);
                HANDLE_CASE_RETURN_STRING(cmdidGotoPrevErrorTagOW);
                HANDLE_CASE_RETURN_STRING(cmdidClearPaneFR1);
                HANDLE_CASE_RETURN_STRING(cmdidGotoErrorTagFR1);
                HANDLE_CASE_RETURN_STRING(cmdidGotoNextErrorTagFR1);
                HANDLE_CASE_RETURN_STRING(cmdidGotoPrevErrorTagFR1);
                HANDLE_CASE_RETURN_STRING(cmdidClearPaneFR2);
                HANDLE_CASE_RETURN_STRING(cmdidGotoErrorTagFR2);
                HANDLE_CASE_RETURN_STRING(cmdidGotoNextErrorTagFR2);
                HANDLE_CASE_RETURN_STRING(cmdidGotoPrevErrorTagFR2);

                // Output Window pane selection dropdown
                HANDLE_CASE_RETURN_STRING(cmdidOutputPaneCombo);
                HANDLE_CASE_RETURN_STRING(cmdidOutputPaneComboList);
                HANDLE_CASE_RETURN_STRING(cmdidDisableDockingChanges);
                HANDLE_CASE_RETURN_STRING(cmdidToggleFloat);
                HANDLE_CASE_RETURN_STRING(cmdidResetLayout);
                HANDLE_CASE_RETURN_STRING(cmdidEditProjectFile);
                HANDLE_CASE_RETURN_STRING(cmdidOpenInFormView);
                HANDLE_CASE_RETURN_STRING(cmdidOpenInCodeView);
                HANDLE_CASE_RETURN_STRING(cmdidExploreFolderInWindows);
                HANDLE_CASE_RETURN_STRING(cmdidNewSolutionFolderBar);
                HANDLE_CASE_RETURN_STRING(cmdidDataShortcut);

                // Tool window navigation
                HANDLE_CASE_RETURN_STRING(cmdidNextToolWindow);
                HANDLE_CASE_RETURN_STRING(cmdidPrevToolWindow);
                HANDLE_CASE_RETURN_STRING(cmdidBrowseToFileInExplorer);
                HANDLE_CASE_RETURN_STRING(cmdidShowEzMDIFileMenu);
                HANDLE_CASE_RETURN_STRING(cmdidNextToolWindowNav);// command for NextToolWindow with navigator
                HANDLE_CASE_RETURN_STRING(cmdidPrevToolWindowNav);

                // One Time build with static anlaysis for ProjOnly
                HANDLE_CASE_RETURN_STRING(cmdidStaticAnalysisOnlyProject);

                //Run Code Analysis on Build Menu
                HANDLE_CASE_RETURN_STRING(ECMD_RUNFXCOPSEL);

                //Run Code Analysis on Context menu for the selected project
                HANDLE_CASE_RETURN_STRING(ECMD_RUNFXCOPPROJCTX);

                HANDLE_CASE_RETURN_STRING(cmdidCloseAllButThis);

                // the numbers from 1650 to 1699 are reserved for Class view  specific commands
                //  CV_COMMANDS_BASE + XXX
                HANDLE_CASE_RETURN_STRING(cmdidCVShowInheritedMembers);
                HANDLE_CASE_RETURN_STRING(cmdidCVShowBaseTypes);
                HANDLE_CASE_RETURN_STRING(cmdidCVShowDerivedTypes);
                HANDLE_CASE_RETURN_STRING(cmdidCVShowHidden);
                HANDLE_CASE_RETURN_STRING(cmdidCVBack);
                HANDLE_CASE_RETURN_STRING(cmdidCVForward);
                HANDLE_CASE_RETURN_STRING(cmdidCVSearchCombo);
                HANDLE_CASE_RETURN_STRING(cmdidCVSearch);
                HANDLE_CASE_RETURN_STRING(cmdidCVSortObjectsAlpha);
                HANDLE_CASE_RETURN_STRING(cmdidCVSortObjectsType);
                HANDLE_CASE_RETURN_STRING(cmdidCVSortObjectsAccess);
                HANDLE_CASE_RETURN_STRING(cmdidCVGroupObjectsType);
                HANDLE_CASE_RETURN_STRING(cmdidCVSortMembersAlpha);
                HANDLE_CASE_RETURN_STRING(cmdidCVSortMembersType);
                HANDLE_CASE_RETURN_STRING(cmdidCVSortMembersAccess);
                HANDLE_CASE_RETURN_STRING(cmdidCVTypeBrowserSettings);
                HANDLE_CASE_RETURN_STRING(cmdidCVViewMembersAsImplementor);
                HANDLE_CASE_RETURN_STRING(cmdidCVViewMembersAsSubclass);
                HANDLE_CASE_RETURN_STRING(cmdidCVViewMembersAsUser);
                HANDLE_CASE_RETURN_STRING(cmdidCVReserved1);
                HANDLE_CASE_RETURN_STRING(cmdidCVReserved2);
                HANDLE_CASE_RETURN_STRING(cmdidCVShowProjectReferences);
                HANDLE_CASE_RETURN_STRING(cmdidCVGroupMembersType);
                HANDLE_CASE_RETURN_STRING(cmdidCVClearSearch);
                HANDLE_CASE_RETURN_STRING(cmdidCVFilterToType);
                HANDLE_CASE_RETURN_STRING(cmdidCVSortByBestMatch);
                HANDLE_CASE_RETURN_STRING(cmdidCVSearchMRUList);
                HANDLE_CASE_RETURN_STRING(cmdidCVViewOtherMembers);
                HANDLE_CASE_RETURN_STRING(cmdidCVSearchCmd);
                HANDLE_CASE_RETURN_STRING(cmdidCVGoToSearchCmd);

                //end of CV commands
                HANDLE_CASE_RETURN_STRING(cmdidControlGallery);
                
                //the numbers from 1710 to 1759 are reserved for Object Browser specific commands
                HANDLE_CASE_RETURN_STRING(cmdidOBShowInheritedMembers);
                HANDLE_CASE_RETURN_STRING(cmdidOBShowBaseTypes);
                HANDLE_CASE_RETURN_STRING(cmdidOBShowDerivedTypes);
                HANDLE_CASE_RETURN_STRING(cmdidOBShowHidden);
                HANDLE_CASE_RETURN_STRING(cmdidOBBack);
                HANDLE_CASE_RETURN_STRING(cmdidOBForward);
                HANDLE_CASE_RETURN_STRING(cmdidOBSearchCombo);
                HANDLE_CASE_RETURN_STRING(cmdidOBSearch);
                HANDLE_CASE_RETURN_STRING(cmdidOBSortObjectsAlpha);
                HANDLE_CASE_RETURN_STRING(cmdidOBSortObjectsType);
                HANDLE_CASE_RETURN_STRING(cmdidOBSortObjectsAccess);
                HANDLE_CASE_RETURN_STRING(cmdidOBGroupObjectsType);
                HANDLE_CASE_RETURN_STRING(cmdidOBSortMembersAlpha);
                HANDLE_CASE_RETURN_STRING(cmdidOBSortMembersType);
                HANDLE_CASE_RETURN_STRING(cmdidOBSortMembersAccess);
                HANDLE_CASE_RETURN_STRING(cmdidOBTypeBrowserSettings);
                HANDLE_CASE_RETURN_STRING(cmdidOBViewMembersAsImplementor);
                HANDLE_CASE_RETURN_STRING(cmdidOBViewMembersAsSubclass);
                HANDLE_CASE_RETURN_STRING(cmdidOBViewMembersAsUser);
                HANDLE_CASE_RETURN_STRING(cmdidOBNamespacesView);
                HANDLE_CASE_RETURN_STRING(cmdidOBContainersView);
                HANDLE_CASE_RETURN_STRING(cmdidOBReserved1);
                HANDLE_CASE_RETURN_STRING(cmdidOBGroupMembersType);
                HANDLE_CASE_RETURN_STRING(cmdidOBClearSearch);
                HANDLE_CASE_RETURN_STRING(cmdidOBFilterToType);
                HANDLE_CASE_RETURN_STRING(cmdidOBSortByBestMatch);
                HANDLE_CASE_RETURN_STRING(cmdidOBSearchMRUList);
                HANDLE_CASE_RETURN_STRING(cmdidOBViewOtherMembers);
                HANDLE_CASE_RETURN_STRING(cmdidOBSearchCmd);
                HANDLE_CASE_RETURN_STRING(cmdidOBGoToSearchCmd);
                HANDLE_CASE_RETURN_STRING(cmdidOBShowExtensionMembers);

                HANDLE_CASE_RETURN_STRING(cmdidFullScreen2);

                // find symbol results sorting command
                HANDLE_CASE_RETURN_STRING(cmdidFSRSortObjectsAlpha);
                HANDLE_CASE_RETURN_STRING(cmdidFSRSortByBestMatch);
                HANDLE_CASE_RETURN_STRING(cmdidNavigateBack);
                HANDLE_CASE_RETURN_STRING(cmdidNavigateForward);

                // Error correction commands (need to be consecutive)
                HANDLE_CASE_RETURN_STRING(ECMD_CORRECTION_1);
                HANDLE_CASE_RETURN_STRING(ECMD_CORRECTION_2);
                HANDLE_CASE_RETURN_STRING(ECMD_CORRECTION_3);
                HANDLE_CASE_RETURN_STRING(ECMD_CORRECTION_4);
                HANDLE_CASE_RETURN_STRING(ECMD_CORRECTION_5);
                HANDLE_CASE_RETURN_STRING(ECMD_CORRECTION_6);
                HANDLE_CASE_RETURN_STRING(ECMD_CORRECTION_7);
                HANDLE_CASE_RETURN_STRING(ECMD_CORRECTION_8);
                HANDLE_CASE_RETURN_STRING(ECMD_CORRECTION_9);
                HANDLE_CASE_RETURN_STRING(ECMD_CORRECTION_10);

                // Object Browser commands
                HANDLE_CASE_RETURN_STRING(cmdidOBAddReference);

                // Edit.FindAllReferences
                HANDLE_CASE_RETURN_STRING(cmdidFindReferences);

                // Code Definition View
                HANDLE_CASE_RETURN_STRING(cmdidCodeDefView);
                HANDLE_CASE_RETURN_STRING(cmdidCodeDefViewGoToPrev);
                HANDLE_CASE_RETURN_STRING(cmdidCodeDefViewGoToNext);
                HANDLE_CASE_RETURN_STRING(cmdidCodeDefViewEditDefinition);
                HANDLE_CASE_RETURN_STRING(cmdidCodeDefViewChooseEncoding);

                // Class view
                HANDLE_CASE_RETURN_STRING(cmdidViewInClassDiagram);

                // Shareable commands from VSDesigner
                HANDLE_CASE_RETURN_STRING(ECMD_ADDDBTABLE);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDDATATABLE);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDFUNCTION);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDRELATION);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDKEY);
                HANDLE_CASE_RETURN_STRING(ECMD_ADDCOLUMN);
                HANDLE_CASE_RETURN_STRING(ECMD_CONVERT_DBTABLE);
                HANDLE_CASE_RETURN_STRING(ECMD_CONVERT_DATATABLE);
                HANDLE_CASE_RETURN_STRING(ECMD_GENERATE_DATABASE);
                HANDLE_CASE_RETURN_STRING(ECMD_CONFIGURE_CONNECTIONS);
                HANDLE_CASE_RETURN_STRING(ECMD_IMPORT_XMLSCHEMA);
                HANDLE_CASE_RETURN_STRING(ECMD_SYNC_WITH_DATABASE);
                HANDLE_CASE_RETURN_STRING(ECMD_CONFIGURE);
                HANDLE_CASE_RETURN_STRING(ECMD_CREATE_DATAFORM);
                HANDLE_CASE_RETURN_STRING(ECMD_CREATE_ENUM);
                HANDLE_CASE_RETURN_STRING(ECMD_INSERT_FUNCTION);
                HANDLE_CASE_RETURN_STRING(ECMD_EDIT_FUNCTION);
                HANDLE_CASE_RETURN_STRING(ECMD_SET_PRIMARY_KEY);
                HANDLE_CASE_RETURN_STRING(ECMD_INSERT_COLUMN);
                HANDLE_CASE_RETURN_STRING(ECMD_AUTO_SIZE);
                HANDLE_CASE_RETURN_STRING(ECMD_SHOW_RELATION_LABELS);


                HANDLE_CASE_RETURN_STRING(cmdid_VSD_GenerateDataSet);
                HANDLE_CASE_RETURN_STRING(cmdid_VSD_Preview);
                HANDLE_CASE_RETURN_STRING(cmdid_VSD_ConfigureAdapter);
                HANDLE_CASE_RETURN_STRING(cmdid_VSD_ViewDatasetSchema);
                HANDLE_CASE_RETURN_STRING(cmdid_VSD_DatasetProperties);
                HANDLE_CASE_RETURN_STRING(cmdid_VSD_ParameterizeForm);
                HANDLE_CASE_RETURN_STRING(cmdid_VSD_AddChildForm);

                HANDLE_CASE_RETURN_STRING(ECMD_EDITCONSTRAINT);
                HANDLE_CASE_RETURN_STRING(ECMD_DELETECONSTRAINT);
                HANDLE_CASE_RETURN_STRING(ECMD_EDITDATARELATION);

                HANDLE_CASE_RETURN_STRING(cmdidCloseProject);
                HANDLE_CASE_RETURN_STRING(cmdidReloadCommandBars);
                HANDLE_CASE_RETURN_STRING(cmdidSolutionPlatform);
                HANDLE_CASE_RETURN_STRING(cmdidSolutionPlatformGetList);

                // Initially used by DataSet Editor
                HANDLE_CASE_RETURN_STRING(ECMD_DATAACCESSOR);
                HANDLE_CASE_RETURN_STRING(ECMD_ADD_DATAACCESSOR);
                HANDLE_CASE_RETURN_STRING(ECMD_QUERY);
                HANDLE_CASE_RETURN_STRING(ECMD_ADD_QUERY);

                // Publish solution
                HANDLE_CASE_RETURN_STRING(ECMD_PUBLISHSELECTION);
                HANDLE_CASE_RETURN_STRING(ECMD_PUBLISHSLNCTX);

                // Call Browser
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowserShowCallsTo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowserShowCallsFrom);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowserShowNewCallsTo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowserShowNewCallsFrom);

                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser1ShowCallsTo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser2ShowCallsTo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser3ShowCallsTo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser4ShowCallsTo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser5ShowCallsTo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser6ShowCallsTo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser7ShowCallsTo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser8ShowCallsTo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser9ShowCallsTo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser10ShowCallsTo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser11ShowCallsTo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser12ShowCallsTo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser13ShowCallsTo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser14ShowCallsTo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser15ShowCallsTo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser16ShowCallsTo);

                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser1ShowCallsFrom);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser2ShowCallsFrom);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser3ShowCallsFrom);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser4ShowCallsFrom);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser5ShowCallsFrom);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser6ShowCallsFrom);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser7ShowCallsFrom);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser8ShowCallsFrom);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser9ShowCallsFrom);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser10ShowCallsFrom);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser11ShowCallsFrom);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser12ShowCallsFrom);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser13ShowCallsFrom);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser14ShowCallsFrom);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser15ShowCallsFrom);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser16ShowCallsFrom);

                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser1ShowFullNames);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser2ShowFullNames);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser3ShowFullNames);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser4ShowFullNames);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser5ShowFullNames);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser6ShowFullNames);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser7ShowFullNames);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser8ShowFullNames);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser9ShowFullNames);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser10ShowFullNames);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser11ShowFullNames);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser12ShowFullNames);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser13ShowFullNames);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser14ShowFullNames);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser15ShowFullNames);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser16ShowFullNames);

                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser1Settings);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser2Settings);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser3Settings);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser4Settings);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser5Settings);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser6Settings);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser7Settings);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser8Settings);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser9Settings);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser10Settings);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser11Settings);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser12Settings);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser13Settings);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser14Settings);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser15Settings);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser16Settings);
                
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser1SortAlpha);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser2SortAlpha);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser3SortAlpha);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser4SortAlpha);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser5SortAlpha);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser6SortAlpha);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser7SortAlpha);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser8SortAlpha);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser9SortAlpha);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser10SortAlpha);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser11SortAlpha);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser12SortAlpha);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser13SortAlpha);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser14SortAlpha);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser15SortAlpha);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser16SortAlpha);

                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser1SortAccess);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser2SortAccess);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser3SortAccess);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser4SortAccess);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser5SortAccess);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser6SortAccess);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser7SortAccess);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser8SortAccess);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser9SortAccess);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser10SortAccess);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser11SortAccess);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser12SortAccess);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser13SortAccess);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser14SortAccess);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser15SortAccess);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser16SortAccess);

                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser1);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser2);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser3);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser4);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser5);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser6);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser7);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser8);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser9);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser10);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser11);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser12);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser13);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser14);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser15);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser16);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser17);

                // Closed file undo
                HANDLE_CASE_RETURN_STRING(cmdidGlobalUndo);
                HANDLE_CASE_RETURN_STRING(cmdidGlobalRedo);

                // Call Browser Commands (No UI, Command window only).
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowserShowCallsToCmd);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowserShowCallsFromCmd);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowserShowNewCallsToCmd);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowserShowNewCallsFromCmd);

                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser1Search);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser2Search);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser3Search);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser4Search);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser5Search);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser6Search);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser7Search);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser8Search);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser9Search);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser10Search);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser11Search);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser12Search);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser13Search);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser14Search);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser15Search);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser16Search);
                
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser1Refresh);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser2Refresh);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser3Refresh);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser4Refresh);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser5Refresh);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser6Refresh);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser7Refresh);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser8Refresh);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser9Refresh);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser10Refresh);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser11Refresh);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser12Refresh);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser13Refresh);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser14Refresh);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser15Refresh);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser16Refresh);

                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser1SearchCombo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser2SearchCombo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser3SearchCombo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser4SearchCombo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser5SearchCombo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser6SearchCombo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser7SearchCombo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser8SearchCombo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser9SearchCombo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser10SearchCombo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser11SearchCombo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser12SearchCombo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser13SearchCombo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser14SearchCombo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser15SearchCombo);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser16SearchCombo);

                // Task List
                HANDLE_CASE_RETURN_STRING(cmdidTaskListProviderCombo);
                HANDLE_CASE_RETURN_STRING(cmdidTaskListProviderComboList);

                // User Task toolbar commands
                HANDLE_CASE_RETURN_STRING(cmdidCreateUserTask);

                // Error List toolbar commands
                HANDLE_CASE_RETURN_STRING(cmdidErrorListShowErrors);
                HANDLE_CASE_RETURN_STRING(cmdidErrorListShowWarnings);
                HANDLE_CASE_RETURN_STRING(cmdidErrorListShowMessages);

                // Product activation (registration)
                HANDLE_CASE_RETURN_STRING(cmdidRegistration);

                // Callbrowser SearchComboList commands
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser1SearchComboList);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser2SearchComboList);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser3SearchComboList);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser4SearchComboList);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser5SearchComboList);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser6SearchComboList);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser7SearchComboList);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser8SearchComboList);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser9SearchComboList);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser10SearchComboList);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser11SearchComboList);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser12SearchComboList);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser13SearchComboList);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser14SearchComboList);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser15SearchComboList);
                HANDLE_CASE_RETURN_STRING(cmdidCallBrowser16SearchComboList);

                //Snippet window buttons
                HANDLE_CASE_RETURN_STRING(cmdidSnippetProp);
                HANDLE_CASE_RETURN_STRING(cmdidSnippetRef);
                HANDLE_CASE_RETURN_STRING(cmdidSnippetRepl);

                //Start Page Command
                HANDLE_CASE_RETURN_STRING(cmdidStartPage);

                // More editor commands
                HANDLE_CASE_RETURN_STRING(cmdidEditorLineFirstColumn);
                HANDLE_CASE_RETURN_STRING(cmdidEditorLineFirstColumnExtend);

                // Server Explorer Menu commands
                HANDLE_CASE_RETURN_STRING(cmdid_SE_ServerExplorer);
                HANDLE_CASE_RETURN_STRING(cmdid_SE_DataExplorer);

                // The following commands form guidDataCmdId.
                HANDLE_CASE_RETURN_STRING(icmdDesign);
                HANDLE_CASE_RETURN_STRING(icmdDesignOn);
                HANDLE_CASE_RETURN_STRING(icmdSEDesign);
                HANDLE_CASE_RETURN_STRING(icmdNewDiagram | cmdid_SE_ToolbarRefresh);
                HANDLE_CASE_RETURN_STRING(icmdNewTable);
                HANDLE_CASE_RETURN_STRING(icmdNewDBItem);
                HANDLE_CASE_RETURN_STRING(icmdNewTrigger);
                HANDLE_CASE_RETURN_STRING(icmdDebug);
                HANDLE_CASE_RETURN_STRING(icmdNewProcedure);
                HANDLE_CASE_RETURN_STRING(icmdNewQuery);
                HANDLE_CASE_RETURN_STRING(icmdRefreshLocal);

                HANDLE_CASE_RETURN_STRING(icmdDbAddDataConnection);
                HANDLE_CASE_RETURN_STRING(icmdDBDefDBRef);
                HANDLE_CASE_RETURN_STRING(icmdRunCmd);
                HANDLE_CASE_RETURN_STRING(icmdRunOn);
                HANDLE_CASE_RETURN_STRING(icmdidNewDBRef);
                HANDLE_CASE_RETURN_STRING(icmdidSetAsDef);
                HANDLE_CASE_RETURN_STRING(icmdidCreateCmdFile);
                HANDLE_CASE_RETURN_STRING(icmdCancel);
                HANDLE_CASE_RETURN_STRING(icmdNewDatabase);
                HANDLE_CASE_RETURN_STRING(icmdNewUser);
                HANDLE_CASE_RETURN_STRING(icmdNewRole);
                HANDLE_CASE_RETURN_STRING(icmdChangeLogin);
                HANDLE_CASE_RETURN_STRING(icmdNewView);
                HANDLE_CASE_RETURN_STRING(icmdModifyConnection);
                HANDLE_CASE_RETURN_STRING(icmdDisconnect);
                HANDLE_CASE_RETURN_STRING(icmdCopyScript);
                HANDLE_CASE_RETURN_STRING(icmdAddSCC);
                HANDLE_CASE_RETURN_STRING(icmdRemoveSCC);
                HANDLE_CASE_RETURN_STRING(icmdGetLatest);
                HANDLE_CASE_RETURN_STRING(icmdCheckOut);
                HANDLE_CASE_RETURN_STRING(icmdCheckIn);
                HANDLE_CASE_RETURN_STRING(icmdUndoCheckOut);
                HANDLE_CASE_RETURN_STRING(icmdAddItemSCC);
                HANDLE_CASE_RETURN_STRING(icmdNewPackageSpec);
                HANDLE_CASE_RETURN_STRING(icmdNewPackageBody);
                HANDLE_CASE_RETURN_STRING(icmdInsertSQL);
                HANDLE_CASE_RETURN_STRING(icmdRunSelection);
                HANDLE_CASE_RETURN_STRING(icmdUpdateScript);
                HANDLE_CASE_RETURN_STRING(icmdCreateScript);
                HANDLE_CASE_RETURN_STRING(icmdSECreateScript);
                HANDLE_CASE_RETURN_STRING(icmdNewScript);
                HANDLE_CASE_RETURN_STRING(icmdNewFunction);
                HANDLE_CASE_RETURN_STRING(icmdNewTableFunction);
                HANDLE_CASE_RETURN_STRING(icmdNewInlineFunction);

                HANDLE_CASE_RETURN_STRING(icmdAddDiagram);
                HANDLE_CASE_RETURN_STRING(icmdAddTable);
                HANDLE_CASE_RETURN_STRING(icmdAddSynonym);
                HANDLE_CASE_RETURN_STRING(icmdAddView);
                HANDLE_CASE_RETURN_STRING(icmdAddProcedure);
                HANDLE_CASE_RETURN_STRING(icmdAddFunction);
                HANDLE_CASE_RETURN_STRING(icmdAddTableFunction);
                HANDLE_CASE_RETURN_STRING(icmdAddInlineFunction);
                HANDLE_CASE_RETURN_STRING(icmdAddPkgSpec);
                HANDLE_CASE_RETURN_STRING(icmdAddPkgBody);
                HANDLE_CASE_RETURN_STRING(icmdAddTrigger);
                HANDLE_CASE_RETURN_STRING(icmdExportData);

                HANDLE_CASE_RETURN_STRING(icmdDbnsVcsAdd);
                HANDLE_CASE_RETURN_STRING(icmdDbnsVcsRemove);
                HANDLE_CASE_RETURN_STRING(icmdDbnsVcsCheckout);
                HANDLE_CASE_RETURN_STRING(icmdDbnsVcsUndoCheckout);
                HANDLE_CASE_RETURN_STRING(icmdDbnsVcsCheckin);
                HANDLE_CASE_RETURN_STRING(icmdSERetrieveData);
                HANDLE_CASE_RETURN_STRING(icmdSEEditTextObject);
                HANDLE_CASE_RETURN_STRING(icmdSERun);
                HANDLE_CASE_RETURN_STRING(icmdSERunSelection);
                HANDLE_CASE_RETURN_STRING(icmdDesignSQLBlock);
                HANDLE_CASE_RETURN_STRING(icmdRegisterSQLInstance);
                HANDLE_CASE_RETURN_STRING(icmdUnregisterSQLInstance);

                // Command Windows submenu commands 0x31xx
                HANDLE_CASE_RETURN_STRING(cmdidCommandWindowSaveScript);
                HANDLE_CASE_RETURN_STRING(cmdidCommandWindowRunScript);
                HANDLE_CASE_RETURN_STRING(cmdidCommandWindowCursorUp);
                HANDLE_CASE_RETURN_STRING(cmdidCommandWindowCursorDown);
                HANDLE_CASE_RETURN_STRING(cmdidCommandWindowCursorLeft);
                HANDLE_CASE_RETURN_STRING(cmdidCommandWindowCursorRight);
                HANDLE_CASE_RETURN_STRING(cmdidCommandWindowHistoryUp);
                HANDLE_CASE_RETURN_STRING(cmdidCommandWindowHistoryDown);

                // from datamenu.h
                HANDLE_CASE_RETURN_STRING(icmdidCmdDTStart);
                HANDLE_CASE_RETURN_STRING(icmdidCmdHeirarchyView0);
                HANDLE_CASE_RETURN_STRING(icmdidCmdHeirarchyView1);
                HANDLE_CASE_RETURN_STRING(icmdidCmdHeirarchyView2);
                HANDLE_CASE_RETURN_STRING(icmdidCmdHeirarchyView3);
                HANDLE_CASE_RETURN_STRING(icmdidCmdHeirarchyView4);
                HANDLE_CASE_RETURN_STRING(icmdidCmdHeirarchyView5);
                HANDLE_CASE_RETURN_STRING(icmdidCmdHeirarchyView6);
                HANDLE_CASE_RETURN_STRING(icmdidCmdHeirarchyView7);
                HANDLE_CASE_RETURN_STRING(icmdidCmdHeirarchyView8);

                HANDLE_CASE_RETURN_STRING(icmdidCmdModify);
                HANDLE_CASE_RETURN_STRING(icmdidCmdClose);
                HANDLE_CASE_RETURN_STRING(icmdidCmdDTLast);

                // Command ids for Server Explorer commands (guid_SE_CommandID group)
                //HANDLE_CASE_RETURN_STRING(cmdid_SE_ToolbarRefresh);    //Same with icmdNewDiagram
                HANDLE_CASE_RETURN_STRING(cmdid_SE_ToolbarStopRefresh);
                HANDLE_CASE_RETURN_STRING(cmdid_SE_AddToForm);
            default:
                FTLTRACEEX(FTL::tlWarning, TEXT("%s : GetStdIdCommandtring CAN NOT Find ID string for %d(0x%x)\n"),
                    __FILE__LINE__, cmdID, cmdID);
                break;
            }
            return TEXT("Unknown");
        }
    };

}

