#pragma once

template <class T>
class CProxy_IFBhoObjectEvents : public IConnectionPointImpl<T, &__uuidof( _IFBhoObjectEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
